baseURL = 'https://higgshomestead.com'
languageCode = 'en-us'
title = 'Higgs Homestead'

[params]
tagline = "Where Texas Hospitality Meets Farm Life"
description = "Experience authentic Texas farm life at Higgs Homestead. Book your peaceful getaway with farm activities, cozy accommodations, and genuine hospitality in the heart of Texas."
keywords = "Texas farm stay, farm getaway, rural vacation, Texas hospitality, farm accommodation, agritourism, Texas retreat"
footer_description = 'Unique Texas farm experience with friendly animals on nearly 10 acres.'

# Location details
city = "Fort Worth"
state = "TX"
zip_code = "76140"
country = "US"
geo_region = "US-TX"
geo_placename = "Fort Worth, Texas"
geo_position = "32.605194,-97.2492711"
#image
og_image = "/images/og-image.webp"


phone = '(817) 727-2129'
email = 'homesbyhiggs@gmail.com'
address_line1 = "5365 Banks Rd"
address_line2 = "Fort Worth, TX 76140"
booking_url = 'https://book.higgshomestead.com'
googleAnalytics = 'G-D1YMHHEEMD'

[params.social]
instagram = 'https://www.instagram.com/higgshomestead/'
facebook = 'https://www.facebook.com/profile.php?id=61577084707758'
airbnb = 'https://www.airbnb.com/users/show/81290702'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Stays'
url = '/stays'
weight = 2

[[menu.main]]
name = 'About'
url = '/about'
weight = 3

[[menu.main]]
name = 'Things to Do'
url = '/things-to-do'
weight = 4

[markup.goldmark.renderer]
unsafe = true
